user_put:
  path: /user/{id}
  controller: Symfony\Base\App\Controller\User\UserPutController
  methods: PUT

user_get:
  path: /user/{id}
  controller: Symfony\Base\App\Controller\User\UserGetController
  methods: GET

user_delete:
  path: /user/{id}
  controller: Symfony\Base\App\Controller\User\UserDeleteController
  methods: DELETE

get_video:
  path: /video/{id}
  controller: Symfony\Base\App\Controller\Videos\GetVideoController
  methods: GET

upsert_video:
  path: /video/{uuid}
  controller: Symfony\Base\App\Controller\Videos\VideoPutController
  methods: PUT

insert_comment:
  path: /comment/{id}
  controller: Symfony\Base\App\Controller\Videos\InsertCommentController
  methods: POST
