user_put:
  path: /user/{id}
  controller: Symfony\Base\App\Controller\User\UserPutController
  methods: PUT

user_get:
  path: /user/{id}
  controller: Symfony\Base\App\Controller\User\UserGetController
  methods: GET

user_delete:
  path: /user/{id}
  controller: Symfony\Base\App\Controller\User\UserDeleteController
  methods: DELETE

get_video:
  path: /video/{id}
  controller: Symfony\Base\App\Controller\Videos\GetVideoController
  methods: GET

upsert_video:
  path: /video/{uuid}
  controller: Symfony\Base\App\Controller\Videos\UpsertVideoController
  methods: PUT

video_delete:
  path: /user/video_delete/{id}
  controller: Symfony\Base\App\Controller\Videos\VideosDeleteController
  methods: DELETE

video_insert:
  path: /user/video_insert/{id}
  controller: Symfony\Base\App\Controller\Videos\VideosInsertController
  methods: POST

insert_comment:
  path: /comment/{id}
  controller: Symfony\Base\App\Controller\Videos\InsertCommentController
  methods: POST
