like-post:
  path: /video/{id}/like
  controller: Symfony\Base\App\Controller\Video\Like\PostLikeController
  methods: POST

video-post:
  path: /video/{id}
  controller: Symfony\Base\App\Controller\Video\Like\PostVideoController
  methods: POST