comment_get:
  path: /comment/{id}
  controller: Symfony\Base\App\Controller\Comment\CommentGetController
  methods: GET

comment_put:
  path: /comment/{id}
  controller: Symfony\Base\App\Controller\Comment\CommentPutController
  methods: PUT

video_get:
  path: /video/{id}
  controller: Symfony\Base\App\Controller\Videos\VideoGetController
  methods: GET

upsert-video:
  path: /video/{uuid}
  controller: Symfony\Base\App\Controller\Videos\UpsertVideoController
  methods: PUT
  
user_put:
  path: /user/{id}
  controller: Symfony\Base\App\Controller\User\UserPutController
  methods: PUT

user_get:
  path: /user/{id}
  controller: Symfony\Base\App\Controller\User\UserGetController
  methods: GET

user_delete:
  path: /user/{id}
  controller: Symfony\Base\App\Controller\User\UserDeleteController
  methods: DELETE