v1_controllers:
  resource: routes/v1/routes.yaml
  prefix: '/v1'

home_get:
  path: /
  controller: Symfony\Base\App\Controller\Home\HomeGetWebController
  defaults: { auth: false }
  methods:  [GET]

user_put:
  path: /user/{id}
  controller: Symfony\Base\App\Controller\User\UserPutController
  methods: PUT

user_get:
  path: /user/{id}
  controller: Symfony\Base\App\Controller\User\UserGetController
  methods: GET

user_delete:
  path: /user/{id}
  controller: Symfony\Base\App\Controller\User\UserDeleteController
  methods: DELETE

video_upsert:
  path: /video/{uuid}
  controller: Symfony\Base\App\Controller\Videos\UpsertVideoController
  methods: PUT

get_video:
  path: /video/{id}
  controller: Symfony\Base\App\Controller\Videos\GetVideoController
  methods: GET

delete_video:
  path: /video/{id}
  controller: Symfony\Base\App\Controller\Videos\DeleteVideoController
  methods: DELETE
