services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Base\App\Controller\:
        resource: '../app/Controller'
        tags: [ 'controller.service_arguments' ]

    Symfony\Base\App\Controller\Videos\:
        resource: '../app/Controller/Videos'
        tags: [ 'controller.service_arguments' ]

    Symfony\Base\App\Listener\:
        resource: '../app/Listener'

    Symfony\Base\:
        resource: '../src/'

    Symfony\Base\App\Listener\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onException }