services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Symfony\Base\Shared\Domain\Bus\Event\DomainEventSubscriber:
            tags: ['symfony.base.domain_event_subscriber']

    Symfony\Base\App\Controller\:
        resource: '../app/Controller'
        tags: [ 'controller.service_arguments' ]

    Symfony\Base\App\Listener\:
        resource: '../app/Listener'

    Symfony\Base\:
        resource: '../src/'

    Symfony\Base\App\Listener\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onException }

    Symfony\Base\Shared\Infrastructure\Bus\Event\InMemorySymfonyEventBus:
        arguments: [ !tagged symfony.base.domain_event_subscriber ]
        lazy: true

    Symfony\Base\Shared\Infrastructure\Bus\Event\DomainEventMapping:
        arguments: [ !tagged symfony.base.domain_event_subscriber ]

    Symfony\Base\Shared\Infrastructure\Bus\Event\DomainEventSubscriberLocator:
        arguments: [ !tagged symfony.base.domain_event_subscriber ]