framework:
    test: true
services:
  _defaults:
    autowire: true
    autoconfigure: true

  Symfony\Base\Tests\:
    resource: '../tests'

  Symfony\Base\Shared\Domain\Bus\Event\EventBus: '@Symfony\Base\Tests\Functional\FakeEventBus'
